## Event and sample space

::: {#def-event}
We use *sets* to build the foundational concepts in probability:

-   **Experiment**: a procedure with an uncertain outcome
-   **Event** $A$: a set of possible outcomes
-   **Sample space** $S$: the set of all possible outcomes
:::

Anything (a gamble, an exam, a financial year, ...) with uncertain
outcomes can be an experiment. The sample space can be finite, countably
infinite, or uncountably infinite. It is convenient to visualize events
with *Venn diagrams*.

::: {.callout-note}
## Don's confuse events with outcomes
Outcomes are individual results, while events are groups of outcomes that we are interested in.
Outcomes are elements of the sample space, and events are subsets of this space.
:::

::: {#exm-1.1}
A coin is flipped twice. We write "H" if a coin lands Head, and "T" if a
coin lands Tail.

- The sample space (all possible outcomes): $S=\left\{ HH,HT,TH,TT\right\}$. 
- Let $A_{1}$ be the event that the first flip is Heads, $A_{1}=\left\{ HH,HT\right\}$. 
- Let $A_{2}$ be the event that the second flip is Heads, $A_{2}=\left\{ HH,TH\right\}$.
- Let $B$ be the event that at least one flip is Heads, $B=A_{1}\cup A_{2}$.
- Let $C$ be the event that all the flips are Heads, $C=A_{1}\cap A_{2}$.
- Let $D$ be the event that no flip is Heads, $D=B^{c}$.
:::

### Use set language to describe events {.unnumbered}

<div>

| English | Sets |
|:-----------------------------------|:----------------------------------:|
| sample space | $S$ |
| $s$ is a possible outcome | $s\in S$ |
| $A$ is an event | $A\subseteq S$ |
| $A$ occurs | $s_{\textrm{actual}}\in A$ |
| $A$ or $B$ occurs | $A\cup B$ |
| Both $A$ and $B$ occur | $A\cap B$ |
| $A$ does not occur | $A^{c}$ |
| at least one of $A_{1},\dots,A_{n}$ | $A_{1}\cup\cdots\cup A_{n}$ |
| all of $A_{1},\dots,A_{n}$ | $A_{1}\cap\cdots\cap A_{n}$ |
| $A$ implies $B$ | $A\subseteq B$ |
| $A$ and $B$ are disjoint (mutually exclusive) | $A\cap B=\phi$ |
| $A_{1},\dots,A_{n}$are a partition of $S$ | $A_{1}\cup\cdots\cup A_{n}=S$ and $A_{i}\cap A_{j}=\phi$ for $i\neq j$ |

</div>
